### ISSUE TITLE
[Bug]: Trying to access array offset on null

### ISSUE THREAD

**Issue by stephenmeehanuk** [marcorieser/statamic-livewire#14]
### Bug description

Hi, 

Wondering what you think might be triggering this error:

```
Trying to access array offset on null {"exception":"[object] (ErrorException(code: 0): Trying to access array offset on null at /home/ploi/website.com/vendor/livewire/livewire/src/Mechanisms/HandleComponents/HandleComponents.php:88)
```

Would this trigger a `500` error?

This error was repeated 77 times in one day between [2025-06-04 20:15:28] and [2025-06-04 22:23:41]

As yet, I'm unable to replicate the issue locally.

I'm using the default `/resources/views/vendor/live-search/dropdown.blade.php` on desktop and a modified copy of that file for mobile `/resources/views/partials/search-mobile.blade.php`

Any suggestions or things to try would be great.

### How to reproduce

That's the problem (sorry), I'm not sure how to reproduce it.

### Logs

```shell
[2025-06-04 20:15:28] production.ERROR: Trying to access array offset on null {"exception":"[object] (ErrorException(code: 0): Trying to access array offset on null at /home/ploi/website.com/vendor/livewire/livewire/src/Mechanisms/HandleComponents/HandleComponents.php:88)
```

### Environment

```yaml
Environment
Application Name: Website
Laravel Version: 11.45.1
PHP Version: 8.3.13
Composer Version: 2.8.9
Environment: production
Debug Mode: OFF
URL: website.com
Maintenance Mode: OFF
Timezone: America/New_York
Locale: en

Cache
Config: CACHED
Events: NOT CACHED
Routes: CACHED
Views: CACHED

Drivers
Broadcasting: pusher
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: redis
Session: redis

Livewire
Livewire: v3.6.3

Statamic
Addons: 6
Sites: 1
Stache Watcher: Disabled
Static Caching: half
Version: 5.57.0 PRO

Statamic Addons
jonassiewertsen/statamic-jobs: 1.5.0
marcorieser/statamic-live-search: 3.0.0
marcorieser/statamic-livewire: 4.5.1
statamic/collaboration: 1.0.0
statamic/importer: 1.8.2
visuellverstehen/statamic-anchor-navigation: 1.0.0
```

### Installation

Other (please explain)

### Additional details

Originally a fresh install a couple of years back, it's been updated as new versions are released.
